apiVersion: v1
kind: Namespace
metadata:
  name: policies
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: rbac-policies
  namespace: policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          rbac: baseline
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: rbac-must-exist
  namespace: policies
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: rbac-roles-and-bindings
      spec:
        remediationAction: enforce
        object-templates:
        # Roles present
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata: { name: ops-namespace-maintainer, namespace: default }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata: { name: developer-deployer-nosecrets, namespace: default }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata: { name: readonly-auditor-nosecrets, namespace: default }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata: { name: ops-namespace-maintainer, namespace: appA }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata: { name: developer-deployer-nosecrets, namespace: appA }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata: { name: readonly-auditor-nosecrets, namespace: appA }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata: { name: ops-namespace-maintainer, namespace: appB }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata: { name: developer-deployer-nosecrets, namespace: appB }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: Role
            metadata: { name: readonly-auditor-nosecrets, namespace: appB }
        # RoleBindings present
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata: { name: ops-admin, namespace: default }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata: { name: developer-edit, namespace: default }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata: { name: readonly-view, namespace: default }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata: { name: ops-admin, namespace: appA }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata: { name: developer-edit, namespace: appA }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata: { name: readonly-view, namespace: appA }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata: { name: ops-admin, namespace: appB }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata: { name: developer-edit, namespace: appB }
        - complianceType: musthave
          objectDefinition:
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata: { name: readonly-view, namespace: appB }
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: bind-rbac-policies
  namespace: policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: rbac-policies
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: rbac-must-exist
