# Bind your IdP groups to the custom Roles

# default
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ops-admin
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
subjects:
- kind: Group
  name: ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ops-namespace-maintainer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-edit
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
subjects:
- kind: Group
  name: developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer-deployer-nosecrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-view
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
subjects:
- kind: Group
  name: readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: readonly-auditor-nosecrets

# app1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ops-admin
  namespace: app1
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
subjects:
- kind: Group
  name: ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ops-namespace-maintainer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-edit
  namespace: app1
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
subjects:
- kind: Group
  name: developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer-deployer-nosecrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-view
  namespace: app1
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
subjects:
- kind: Group
  name: readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: readonly-auditor-nosecrets

# app2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ops-admin
  namespace: app2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
subjects:
- kind: Group
  name: ops
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ops-namespace-maintainer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-edit
  namespace: app2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
subjects:
- kind: Group
  name: developer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer-deployer-nosecrets
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-view
  namespace: app2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
subjects:
- kind: Group
  name: readonly
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: readonly-auditor-nosecrets
---
# ---- Membership bindings to make projects visible in CLI/console ----
# app1
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: membership-view-readonly
  namespace: app1
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: readonly
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: membership-view-developer
  namespace: app1
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: developer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: membership-view-ops
  namespace: app1
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: ops
---
# app2
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: membership-view-readonly
  namespace: app2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: readonly
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: membership-view-developer
  namespace: app2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: developer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: membership-view-ops
  namespace: app2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
- kind: Group
  apiGroup: rbac.authorization.k8s.io
  name: ops

