apiVersion: v1
kind: ConfigMap
metadata:
  name: acm-placement
  namespace: openshift-gitops
data:
  apiVersion: cluster.open-cluster-management.io/v1beta1
  kind: PlacementDecision
  statusListKey: decisions
  labelSelectorKey: cluster.open-cluster-management.io/placement
  clusterNameKey: clusterName
  clusterNamespaceKey: clusterNamespace
