apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: rbac-baseline
  namespace: openshift-gitops
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchLabels:
          rbac: baseline
